# Generated by Django 5.2.4 on 2025-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('specialization', models.CharField(max_length=100, verbose_name='Спеціалізація')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактний телефон')),
            ],
        ),
    ]
